### ISSUE TITLE
[Bug] Boolean mistake

### ISSUE THREAD

**Issue by emisjerry** [pistacchio/obsidian-enhanced-tables#1]
There's an error in your sample:

```
Boolean:
    type: bool
    yes-format: '👍'
    no-format: '👎'
```

In the table's header: Bool
It should be Boolean.

BTW, i like this plugin. 👍
