### ISSUE TITLE
Cannot parse the YAML configuration

### ISSUE THREAD

**Issue by flodi** [pistacchio/obsidian-enhanced-tables#9]
Hi, just trying the plugin, but I get this error with this page:

```yaml enhanced-tables
sort: Titolo
hide-configuration: true
editable: true

columns:
	Titolo:
		searchable: true
```

| Titolo                      | Prossimo numero |
| --------------------------- | --------------- |
| Teogonia                    | 3               |
| Gachiakuta                  | 3               |
| Kaina of the great snow sea | 2               |
| God Mazinger                | 2               |
| Devilman Saga               | 3               |
| The Prism                   | 3               |
| Dorohedoro                  | 7               |
| One Punch Man               | 11              |
| Department of Truth         | 4               |
| Mr. Evidence                | 3               |
| Brzkr                       | 3               |
| Divina Congrega             | 3               |
| Seven to eternity           | 3               |
